// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package rest

import (
	"time"
)

// Defines values for OrderStatus.
const (
	ORDERSTATUSCANCELLED   OrderStatus = "ORDER_STATUS_CANCELLED"
	ORDERSTATUSDELIVERED   OrderStatus = "ORDER_STATUS_DELIVERED"
	ORDERSTATUSPAID        OrderStatus = "ORDER_STATUS_PAID"
	ORDERSTATUSPENDING     OrderStatus = "ORDER_STATUS_PENDING"
	ORDERSTATUSSHIPPED     OrderStatus = "ORDER_STATUS_SHIPPED"
	ORDERSTATUSUNSPECIFIED OrderStatus = "ORDER_STATUS_UNSPECIFIED"
)

// Order defines model for Order.
type Order struct {
	// CreatedAt Timestamp when the order was created
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Id Unique identifier of the order
	Id string `json:"id"`

	// Items List of items in the order
	Items []OrderItem `json:"items"`

	// Status Current status of the order
	Status OrderStatus `json:"status"`

	// TotalAmount Total amount of the order
	TotalAmount float64 `json:"total_amount"`

	// UpdatedAt Timestamp when the order was last updated
	UpdatedAt *time.Time `json:"updated_at,omitempty"`

	// UserId ID of the user who placed the order
	UserId string `json:"user_id"`
}

// OrderItem defines model for OrderItem.
type OrderItem struct {
	// Name Name of the product
	Name string `json:"name"`

	// ProductId ID of the product
	ProductId string `json:"product_id"`

	// Quantity Quantity of the product
	Quantity int32 `json:"quantity"`

	// Subtotal Total price for this item
	Subtotal float64 `json:"subtotal"`

	// UnitPrice Price per unit
	UnitPrice float64 `json:"unit_price"`
}

// OrderStatus Current status of the order
type OrderStatus string

// ListOrdersParams defines parameters for ListOrders.
type ListOrdersParams struct {
	UserId    string  `form:"user_id" json:"user_id"`
	PageSize  *int    `form:"page_size,omitempty" json:"page_size,omitempty"`
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateOrderJSONBody defines parameters for CreateOrder.
type CreateOrderJSONBody struct {
	Items  []OrderItem `json:"items"`
	UserId string      `json:"user_id"`
}

// UpdateOrderStatusJSONBody defines parameters for UpdateOrderStatus.
type UpdateOrderStatusJSONBody struct {
	// Status Current status of the order
	Status OrderStatus `json:"status"`
}

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody CreateOrderJSONBody

// UpdateOrderStatusJSONRequestBody defines body for UpdateOrderStatus for application/json ContentType.
type UpdateOrderStatusJSONRequestBody UpdateOrderStatusJSONBody
