// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: stockpb/stock.proto

package stockpb

import (
	orderpb "github.com/hw1513/ecomm/common/genproto/orderpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StockOperation represents a stock operation type
type StockOperation int32

const (
	StockOperation_STOCK_OPERATION_UNSPECIFIED StockOperation = 0
	StockOperation_STOCK_OPERATION_DEDUCT      StockOperation = 1 // Deduct stock (e.g., when order is created)
	StockOperation_STOCK_OPERATION_RESTORE     StockOperation = 2 // Restore stock (e.g., when order is cancelled)
)

// Enum value maps for StockOperation.
var (
	StockOperation_name = map[int32]string{
		0: "STOCK_OPERATION_UNSPECIFIED",
		1: "STOCK_OPERATION_DEDUCT",
		2: "STOCK_OPERATION_RESTORE",
	}
	StockOperation_value = map[string]int32{
		"STOCK_OPERATION_UNSPECIFIED": 0,
		"STOCK_OPERATION_DEDUCT":      1,
		"STOCK_OPERATION_RESTORE":     2,
	}
)

func (x StockOperation) Enum() *StockOperation {
	p := new(StockOperation)
	*p = x
	return p
}

func (x StockOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StockOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_stockpb_stock_proto_enumTypes[0].Descriptor()
}

func (StockOperation) Type() protoreflect.EnumType {
	return &file_stockpb_stock_proto_enumTypes[0]
}

func (x StockOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StockOperation.Descriptor instead.
func (StockOperation) EnumDescriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{0}
}

// Stock represents the current stock level of a product
type Stock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stock) Reset() {
	*x = Stock{}
	mi := &file_stockpb_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{0}
}

func (x *Stock) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Stock) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Stock) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CheckStockRequest represents a request to check stock availability
type CheckStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*orderpb.OrderItem   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // Check stock for multiple items in an order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStockRequest) Reset() {
	*x = CheckStockRequest{}
	mi := &file_stockpb_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockRequest) ProtoMessage() {}

func (x *CheckStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockRequest.ProtoReflect.Descriptor instead.
func (*CheckStockRequest) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{1}
}

func (x *CheckStockRequest) GetItems() []*orderpb.OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// CheckStockResponse represents a response to checking stock availability
type CheckStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable   bool                   `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	ItemStatus    []*StockStatus         `protobuf:"bytes,2,rep,name=item_status,json=itemStatus,proto3" json:"item_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStockResponse) Reset() {
	*x = CheckStockResponse{}
	mi := &file_stockpb_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockResponse) ProtoMessage() {}

func (x *CheckStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockResponse.ProtoReflect.Descriptor instead.
func (*CheckStockResponse) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{2}
}

func (x *CheckStockResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *CheckStockResponse) GetItemStatus() []*StockStatus {
	if x != nil {
		return x.ItemStatus
	}
	return nil
}

// StockStatus represents the stock status for a specific product
type StockStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductId         string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	IsAvailable       bool                   `protobuf:"varint,2,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	AvailableQuantity int32                  `protobuf:"varint,3,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	RequiredQuantity  int32                  `protobuf:"varint,4,opt,name=required_quantity,json=requiredQuantity,proto3" json:"required_quantity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StockStatus) Reset() {
	*x = StockStatus{}
	mi := &file_stockpb_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockStatus) ProtoMessage() {}

func (x *StockStatus) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockStatus.ProtoReflect.Descriptor instead.
func (*StockStatus) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{3}
}

func (x *StockStatus) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockStatus) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *StockStatus) GetAvailableQuantity() int32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

func (x *StockStatus) GetRequiredQuantity() int32 {
	if x != nil {
		return x.RequiredQuantity
	}
	return 0
}

// UpdateStockRequest represents a request to update stock
type UpdateStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                                       // Reference to the order
	OrderStatus   orderpb.OrderStatus    `protobuf:"varint,2,opt,name=order_status,json=orderStatus,proto3,enum=orderpb.OrderStatus" json:"order_status,omitempty"` // Current order status
	Items         []*orderpb.OrderItem   `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`                                                          // Items to update stock for
	Operation     StockOperation         `protobuf:"varint,4,opt,name=operation,proto3,enum=stockpb.StockOperation" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockRequest) Reset() {
	*x = UpdateStockRequest{}
	mi := &file_stockpb_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockRequest) ProtoMessage() {}

func (x *UpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateStockRequest) GetOrderStatus() orderpb.OrderStatus {
	if x != nil {
		return x.OrderStatus
	}
	return orderpb.OrderStatus(0)
}

func (x *UpdateStockRequest) GetItems() []*orderpb.OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *UpdateStockRequest) GetOperation() StockOperation {
	if x != nil {
		return x.Operation
	}
	return StockOperation_STOCK_OPERATION_UNSPECIFIED
}

// UpdateStockResponse represents a response to updating stock
type UpdateStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedStocks []*Stock               `protobuf:"bytes,1,rep,name=updated_stocks,json=updatedStocks,proto3" json:"updated_stocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockResponse) Reset() {
	*x = UpdateStockResponse{}
	mi := &file_stockpb_stock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockResponse) ProtoMessage() {}

func (x *UpdateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockResponse.ProtoReflect.Descriptor instead.
func (*UpdateStockResponse) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStockResponse) GetUpdatedStocks() []*Stock {
	if x != nil {
		return x.UpdatedStocks
	}
	return nil
}

// GetStockRequest represents a request to get stock by product ID
type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_stockpb_stock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{6}
}

func (x *GetStockRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// GetStockResponse represents a response to getting stock
type GetStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         *Stock                 `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockResponse) Reset() {
	*x = GetStockResponse{}
	mi := &file_stockpb_stock_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockResponse) ProtoMessage() {}

func (x *GetStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockResponse.ProtoReflect.Descriptor instead.
func (*GetStockResponse) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{7}
}

func (x *GetStockResponse) GetStock() *Stock {
	if x != nil {
		return x.Stock
	}
	return nil
}

var File_stockpb_stock_proto protoreflect.FileDescriptor

const file_stockpb_stock_proto_rawDesc = "" +
	"\n" +
	"\x13stockpb/stock.proto\x12\astockpb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13orderpb/order.proto\"}\n" +
	"\x05Stock\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"=\n" +
	"\x11CheckStockRequest\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.orderpb.OrderItemR\x05items\"n\n" +
	"\x12CheckStockResponse\x12!\n" +
	"\fis_available\x18\x01 \x01(\bR\visAvailable\x125\n" +
	"\vitem_status\x18\x02 \x03(\v2\x14.stockpb.StockStatusR\n" +
	"itemStatus\"\xab\x01\n" +
	"\vStockStatus\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fis_available\x18\x02 \x01(\bR\visAvailable\x12-\n" +
	"\x12available_quantity\x18\x03 \x01(\x05R\x11availableQuantity\x12+\n" +
	"\x11required_quantity\x18\x04 \x01(\x05R\x10requiredQuantity\"\xc9\x01\n" +
	"\x12UpdateStockRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x127\n" +
	"\forder_status\x18\x02 \x01(\x0e2\x14.orderpb.OrderStatusR\vorderStatus\x12(\n" +
	"\x05items\x18\x03 \x03(\v2\x12.orderpb.OrderItemR\x05items\x125\n" +
	"\toperation\x18\x04 \x01(\x0e2\x17.stockpb.StockOperationR\toperation\"L\n" +
	"\x13UpdateStockResponse\x125\n" +
	"\x0eupdated_stocks\x18\x01 \x03(\v2\x0e.stockpb.StockR\rupdatedStocks\"0\n" +
	"\x0fGetStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"8\n" +
	"\x10GetStockResponse\x12$\n" +
	"\x05stock\x18\x01 \x01(\v2\x0e.stockpb.StockR\x05stock*j\n" +
	"\x0eStockOperation\x12\x1f\n" +
	"\x1bSTOCK_OPERATION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16STOCK_OPERATION_DEDUCT\x10\x01\x12\x1b\n" +
	"\x17STOCK_OPERATION_RESTORE\x10\x022\xe0\x01\n" +
	"\fStockService\x12E\n" +
	"\n" +
	"CheckStock\x12\x1a.stockpb.CheckStockRequest\x1a\x1b.stockpb.CheckStockResponse\x12H\n" +
	"\vUpdateStock\x12\x1b.stockpb.UpdateStockRequest\x1a\x1c.stockpb.UpdateStockResponse\x12?\n" +
	"\bGetStock\x12\x18.stockpb.GetStockRequest\x1a\x19.stockpb.GetStockResponseB9Z7github.com/hw1513/ecomm/common/genproto/stockpb;stockpbb\x06proto3"

var (
	file_stockpb_stock_proto_rawDescOnce sync.Once
	file_stockpb_stock_proto_rawDescData []byte
)

func file_stockpb_stock_proto_rawDescGZIP() []byte {
	file_stockpb_stock_proto_rawDescOnce.Do(func() {
		file_stockpb_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stockpb_stock_proto_rawDesc), len(file_stockpb_stock_proto_rawDesc)))
	})
	return file_stockpb_stock_proto_rawDescData
}

var file_stockpb_stock_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stockpb_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_stockpb_stock_proto_goTypes = []any{
	(StockOperation)(0),           // 0: stockpb.StockOperation
	(*Stock)(nil),                 // 1: stockpb.Stock
	(*CheckStockRequest)(nil),     // 2: stockpb.CheckStockRequest
	(*CheckStockResponse)(nil),    // 3: stockpb.CheckStockResponse
	(*StockStatus)(nil),           // 4: stockpb.StockStatus
	(*UpdateStockRequest)(nil),    // 5: stockpb.UpdateStockRequest
	(*UpdateStockResponse)(nil),   // 6: stockpb.UpdateStockResponse
	(*GetStockRequest)(nil),       // 7: stockpb.GetStockRequest
	(*GetStockResponse)(nil),      // 8: stockpb.GetStockResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*orderpb.OrderItem)(nil),     // 10: orderpb.OrderItem
	(orderpb.OrderStatus)(0),      // 11: orderpb.OrderStatus
}
var file_stockpb_stock_proto_depIdxs = []int32{
	9,  // 0: stockpb.Stock.updated_at:type_name -> google.protobuf.Timestamp
	10, // 1: stockpb.CheckStockRequest.items:type_name -> orderpb.OrderItem
	4,  // 2: stockpb.CheckStockResponse.item_status:type_name -> stockpb.StockStatus
	11, // 3: stockpb.UpdateStockRequest.order_status:type_name -> orderpb.OrderStatus
	10, // 4: stockpb.UpdateStockRequest.items:type_name -> orderpb.OrderItem
	0,  // 5: stockpb.UpdateStockRequest.operation:type_name -> stockpb.StockOperation
	1,  // 6: stockpb.UpdateStockResponse.updated_stocks:type_name -> stockpb.Stock
	1,  // 7: stockpb.GetStockResponse.stock:type_name -> stockpb.Stock
	2,  // 8: stockpb.StockService.CheckStock:input_type -> stockpb.CheckStockRequest
	5,  // 9: stockpb.StockService.UpdateStock:input_type -> stockpb.UpdateStockRequest
	7,  // 10: stockpb.StockService.GetStock:input_type -> stockpb.GetStockRequest
	3,  // 11: stockpb.StockService.CheckStock:output_type -> stockpb.CheckStockResponse
	6,  // 12: stockpb.StockService.UpdateStock:output_type -> stockpb.UpdateStockResponse
	8,  // 13: stockpb.StockService.GetStock:output_type -> stockpb.GetStockResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_stockpb_stock_proto_init() }
func file_stockpb_stock_proto_init() {
	if File_stockpb_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stockpb_stock_proto_rawDesc), len(file_stockpb_stock_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stockpb_stock_proto_goTypes,
		DependencyIndexes: file_stockpb_stock_proto_depIdxs,
		EnumInfos:         file_stockpb_stock_proto_enumTypes,
		MessageInfos:      file_stockpb_stock_proto_msgTypes,
	}.Build()
	File_stockpb_stock_proto = out.File
	file_stockpb_stock_proto_goTypes = nil
	file_stockpb_stock_proto_depIdxs = nil
}
