openapi: 3.0.0
info:
  title: Order Service API
  description: API for managing customer orders
  version: 1.0.0

servers:
  - url: http://localhost:8081
    description: Local development server

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the order
        user_id:
          type: string
          description: ID of the user who placed the order
        items:
          type: array
          items:
            $ref: "#/components/schemas/OrderItem"
          description: List of items in the order
        total_amount:
          type: number
          format: double
          description: Total amount of the order
        status:
          $ref: "#/components/schemas/OrderStatus"
        created_at:
          type: string
          format: date-time
          description: Timestamp when the order was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the order was last updated
      required:
        - id
        - user_id
        - items
        - total_amount
        - status

    OrderItem:
      type: object
      properties:
        product_id:
          type: string
          description: ID of the product
        name:
          type: string
          description: Name of the product
        quantity:
          type: integer
          format: int32
          description: Quantity of the product
        unit_price:
          type: number
          format: double
          description: Price per unit
        subtotal:
          type: number
          format: double
          description: Total price for this item
      required:
        - product_id
        - name
        - quantity
        - unit_price
        - subtotal

    OrderStatus:
      type: string
      enum:
        - ORDER_STATUS_UNSPECIFIED
        - ORDER_STATUS_PENDING
        - ORDER_STATUS_PAID
        - ORDER_STATUS_SHIPPED
        - ORDER_STATUS_DELIVERED
        - ORDER_STATUS_CANCELLED
      description: Current status of the order

paths:
  /v1/orders:
    post:
      summary: Create a new order
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                items:
                  type: array
                  items:
                    $ref: "#/components/schemas/OrderItem"
              required:
                - user_id
                - items
      responses:
        "200":
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "400":
          description: Invalid request
        "500":
          description: Internal server error

    get:
      summary: List orders
      operationId: listOrders
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
        - name: page_size
          in: query
          schema:
            type: integer
            default: 10
        - name: page_token
          in: query
          schema:
            type: string
      responses:
        "200":
          description: List of orders
          content:
            application/json:
              schema:
                type: object
                properties:
                  orders:
                    type: array
                    items:
                      $ref: "#/components/schemas/Order"
                  next_page_token:
                    type: string
        "400":
          description: Invalid request
        "500":
          description: Internal server error

  /v1/orders/{order_id}:
    get:
      summary: Get order by ID
      operationId: getOrder
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Order details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "404":
          description: Order not found
        "500":
          description: Internal server error

    patch:
      summary: Update order status
      operationId: updateOrderStatus
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  $ref: "#/components/schemas/OrderStatus"
              required:
                - status
      responses:
        "200":
          description: Order status updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "404":
          description: Order not found
        "500":
          description: Internal server error
